name: expensy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.0-177.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_admin_scaffold: ^1.4.0
  flutter_bloc: ^9.1.1
  expensy_common:
    path: packages/common/expensy_common
  expensy_dashboard_presentation:  
    path: packages/presentations/expensy_dashboard_presentation
  expensy_expenses_add_new_expense_form_presentation:  
    path: packages/presentations/expensy_expenses_add_new_expense_form_presentation
  expensy_expenses_list_item_details_presentation:  
    path: packages/presentations/expensy_expenses_list_item_details_presentation
  expensy_expenses_list_presentation:  
    path: packages/presentations/expensy_expenses_list_presentation
  expensy_settings_presentation:  
    path: packages/presentations/expensy_settings_presentation
  expensy_sign_in_presentation:  
    path: packages/presentations/expensy_sign_in_presentation
  expensy_sign_up_presentation:  
    path: packages/presentations/expensy_sign_up_presentation
  expensy_splash_presentation:  
    path: packages/presentations/expensy_splash_presentation
  expensy_welcome_presentation:  
    path: packages/presentations/expensy_welcome_presentation
  expensy_firebase:
    path: packages/data-source/firebase/expensy_firebase
  expensy_layouts:
    path: packages/layout/expensy_layouts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
