name: expensy_common
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0-177.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  expensy_authentication_remote_data_source:
    path: ../../data-source/remote/expensy_authentication_remote_data_source
  font_awesome_flutter: ^10.8.0
  expensy_firebase:
    path: ../../data-source/firebase/expensy_firebase
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/images/
