name: expensy_expenses_list_presentation
description: "A new Flutter package project."
version: 0.0.1
homepage:
environment:
  sdk: ^3.8.0-177.0.dev
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  expensy_common:
    path: ../../common/expensy_common
  loading_animation_widget: ^1.3.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  expensy_expenses_list_remote_data_source:
    path: ../../data-source/remote/expensy_expenses_list_remote_data_source
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
