name: expensy_welcome_presentation
description: "A new Flutter package project."
version: 0.0.1
homepage:
environment:
  sdk: ^3.8.0-177.0.dev
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  expensy_common:
    path: ../../common/expensy_common
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/
    - assets/images/
